# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: pgrellie <pgrellie@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/06/18 14:56:45 by pgrellie          #+#    #+#              #
#    Updated: 2024/07/18 18:06:55 by pgrellie         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

#########################################################
# TERMINAL COLORS OP ##

NORMAL = \033[0;39m
GRAY = \033[0;90m
RED = \033[0;91m
GREEN = \033[0;92m
YELLOW = \033[0;93m
BLUE = \033[0;94m
MAGENTA = \033[0;95m
CYAN = \033[0;96m
WHITE = \033[0;97m
EPIX_WHITE = \033[5;97m
EPIX_GREEN = \033[5;92m

##########################################################
##### FOLDERS PATH ####

SRCS_DIR = ./srcs_mandatory/
SRCS_BONUS_DIR = ./srcs_bonus/
OBJS_DIR = ./Objs/
LIBS_DIR = ./Libraries/
BIN_DIR = ./bin/
HEADER_DIR = ./Includes/

#########################################################
###### ARGUMENTS ######

NAME = pipex
BONUS_NAME = pipex_bonus
CFLAGS = -Wall -Werror -Wextra
LDFLAGS = -lpedro_lib
COMP = cc
RM = rm -rf
MKDIR = mkdir -p

##########################################################
### LIBRARIES PATH ####

LIBFT_DOSS = $(LIBS_DIR)pedro_lib/
LIBFT_MAKE_COMMAND = make -s -C $(LIBFT_DOSS) --no-print-directory
LIBFT_PATH = $(LIBFT_DOSS)pedro_lib.a

##########################################################
###### INCLUDES  ######

INCLUDES = -I $(LIBFT_PATH)
PATH_OF_THE_LIBS = -L $(LIBFT_DOSS)

##########################################################
######  SOURCES  ######
SRCS_FILES = pipex.c\
				init_struct.c\
				wait_da_boy.c\
				redirector.c\
				child_process.c\
				cmd_path.c\
				cmd_exec.c\
				file_opener.c\
				find_env.c\
				exit_brr.c\

SRCS = $(addprefix $(SRCS_DIR), $(SRCS_FILES))

SRCS_FILES_BONUS = pipex_bonus.c\

SRCS_BONUS = $(addprefix $(SRCS_BONUS_DIR), $(SRCS_BONUS_FILES))				

##########################################################
######  OBJECTS  ######

OBJS_FILES = $(patsubst %.c, $(OBJS_DIR)%.o, $(SRCS_FILES))
OBJS = $(addprefix $(OBJS_DIR), $(OBJS_FILES))

OBJS_BONUS_FILES = $(patsubst %.c, $(OBJS_BONUS_DIR)%.o, $(SRCS_BONUS_FILES))
OBJS_BONUS = $(addprefix $(OBJS_BONUS_DIR), $(OBJS_BONUS_FILES))

##########################################################
######   RULES   ######

all: $(NAME)
	
$(NAME) : $(OBJS_DIR) $(OBJS_FILES)
	@echo "$(GREEN)\n<<< Done >>>\n$(NORMAL)"
	@echo "$(YELLOW)\nBuilding project ...\n$(NORMAL)"
#	@$(MKDIR) $(BIN_DIR)
	@$(LIBFT_MAKE_COMMAND)
	@$(COMP) $(CFLAGS) $(OBJS_FILES) -o $(NAME) $(PATH_OF_THE_LIBS) $(LDFLAGS)
	@echo "$(GREEN)\n<<< [PIPEX] has been compiled >>>\n" 
	@echo "$(EPIX_WHITE)                   /!\/!\/!\/!\/!\/!\ \n$(NORMAL)" 
	@echo "$(WHITE) Use this command : ./bin/pipex infile cmd1 cmd2 outfile\n$(NORMAL)"

bonus: $(BONUS_NAME)

$(BONUS_NAME) : $(OBJS_BONUS_DIR) $(OBJS_BONUS_FILES)
	@echo "$(GREEN)\n<<< Done >>>\n$(NORMAL)"
	@echo "$(YELLOW)\nBuilding bonus ...\n$(NORMAL)"
	@$(LIBFT_MAKE_COMMAND)
	@$(COMP) $(CFLAGS) $(OBJS_BONUS_FILES) -o $(NAME_BONUS) $(PATH_OF_THE_LIBS) $(LDFLAGS)
	@echo "$(GREEN)\n<<< [PIPEX_BONUS] has been compiled >>>\n" 
	@echo "$(EPIX_WHITE)                   /!\/!\/!\/!\/!\/!\ \n$(NORMAL)" 
	@echo "$(WHITE) Use this command : ./bin/pipex_bonus infile cmd1 cmd2 outfile\n$(NORMAL)"
	
#Creer le repertoire 'Objs' et compiles C source files into object files
$(OBJS_DIR):
	@echo "$(YELLOW)\nProcessing c files into o files ...\n$(NORMAL)"
	@$(MKDIR) $(OBJS_DIR)

$(OBJS_DIR)%.o: $(SRCS_DIR)%.c
	@$(COMP) $(CFLAGS) -I $(HEADER_DIR) -c $< -o $@

$(OBJS_BONUS_DIR):
	@echo "$(YELLOW)\nProcessing bonus c files into o files ...\n$(NORMAL)"
	@$(MKDIR) $(OBJS_BONUS_DIR)

$(OBJS_BONUS_DIR):
	@$(COMP) $(CFLAGS) -I $(HEADER_DIR) -c $< -o $@

#Clean objects files and dependencies
clean:
	@$(RM) $(OBJS_DIR) $(OBJS_BONUS_DIR)
	@make clean -C $(LIBFT_DOSS) --no-print-directory
	@echo "$(MAGENTA)\n<<< Object files have been removed >>>\n$(NORMAL)"

#Cleans everething generated by the Makefile
fclean: clean
	@$(RM) $(NAME) $(NAME_BONUS) $(OBJS_DIR) $(OBJS_BONUS_DIR)
	@make fclean -C $(LIBFT_DOSS) --no-print-directory
	@echo "$(MAGENTA)\n<<< Executable files, object files and Directories have been removed >>>\n$(NORMAL)"

#Remake	
re: fclean all

.PHONY: all clean fclean re libpedro_lib